import { DEALER_PLANS, type PlanId } from './plans';

// ─── INVOICE GENERATION ──────────────────────────────────────────────────────
// One place that knows how to build an invoice, used by the monthly cron, by ad
// approval, and by the manual form in the CRM.
//
// WHY IT IS SHARED
// Invoices raised three different ways would otherwise compute VAT three
// different ways and number themselves three different ways. The first time
// that matters is when SARS asks why invoice GX-2026-0041 and GX-2026-0042 use
// different rounding.
//
// VAT NOTE. GX SA (Pty) Ltd is only obliged to register for VAT once taxable
// supplies exceed R1 million in any twelve months. Until then invoices should
// carry NO VAT and must not be called tax invoices — charging VAT while
// unregistered is an offence under section 58 of the VAT Act. Set
// VAT_REGISTERED to true, and VAT_NUMBER, on the day registration completes.

export const VAT_REGISTERED = false;
export const VAT_NUMBER: string | null = null;
export const VAT_RATE = 15;

export interface InvoiceLine {
  description: string;
  amount: number;
}

export interface BuiltInvoice {
  invoice_number: string;
  client_type: string;
  client_id: string | null;
  client_name: string;
  client_email: string;
  description: string;
  line_items: InvoiceLine[];
  subtotal: number;
  vat: number;
  total: number;
  status: string;
  due_date: string;
  notes: string;
  auto_generated: boolean;
}

/**
 * GX-2026-0001. Sequential within the year, which is what an auditor expects —
 * a gap should mean a cancelled invoice, not a random identifier.
 */
export function nextInvoiceNumber(year: number, countThisYear: number): string {
  return `GX-${year}-${String(countThisYear + 1).padStart(4, '0')}`;
}

export function buildInvoice(input: {
  invoiceNumber: string;
  clientType: string;
  clientId?: string | null;
  clientName: string;
  clientEmail: string;
  description: string;
  lines: InvoiceLine[];
  dueInDays?: number;
  notes?: string;
  autoGenerated?: boolean;
}): BuiltInvoice {
  const subtotal = input.lines.reduce((s, l) => s + (Number(l.amount) || 0), 0);

  // Rounded to the cent, not the rand. Rounding each invoice to the nearest
  // rand drifts by real money across a year of subscriptions.
  const vat = VAT_REGISTERED ? Math.round(subtotal * VAT_RATE) / 100 : 0;

  const due = new Date();
  due.setDate(due.getDate() + (input.dueInDays ?? 14));

  return {
    invoice_number: input.invoiceNumber,
    client_type: input.clientType,
    client_id: input.clientId ?? null,
    client_name: input.clientName,
    client_email: input.clientEmail,
    description: input.description,
    line_items: input.lines,
    subtotal,
    vat,
    total: subtotal + vat,
    status: 'unpaid',
    due_date: due.toISOString().slice(0, 10),
    notes: input.notes || (VAT_REGISTERED
      ? `VAT No. ${VAT_NUMBER}`
      : 'GX SA (Pty) Ltd is not a registered VAT vendor. No VAT is charged on this invoice.'),
    auto_generated: input.autoGenerated ?? false,
  };
}

/** What a dealer on a given tier owes for one month. */
export function dealerMonthlyLine(tier: string, monthLabel: string): InvoiceLine | null {
  const plan = DEALER_PLANS[tier as PlanId];
  if (!plan || plan.price <= 0) return null;
  return {
    description: `${plan.label} dealer subscription — ${monthLabel}`,
    amount: plan.price,
  };
}

export const CLUB_MONTHLY_PRICE = 399;

export function clubMonthlyLine(monthLabel: string): InvoiceLine {
  return {
    description: `Club & range subscription — ${monthLabel}`,
    amount: CLUB_MONTHLY_PRICE,
  };
}